### ISSUE TITLE
Quotes in the README example are not needed

### ISSUE THREAD

**Issue by thomaska** [twitter/diffy#11]
I tried following the steps described in README.md to try out and test diffy,<br>
but I would get MatchErrors when trying the command:
<code>
java -jar diffy-server.jar \
-candidate=\"localhost:9992\" \
-master.primary=\"localhost:9990\" \
-master.secondary=\"localhost:9991\" \
-service.protocol=\"http\" \
-serviceName=\"My Service\" \
-proxy.port=:31900 \
-admin.port=:31159 \
-http.port=:31149 \
-rootUrl='localhost:31149'
</code>
I had to remove the quotes along with the corresponding escape characters for it to work.<br>
I was using a terminal in OS X Yosemite, I don't know if that matters.

**Comment by mosesn** [comment]
@thomaska does it work if you just remove the escape characters?  Like so:

```bash
java -jar diffy-server.jar \
-candidate="localhost:9992" \
-master.primary="localhost:9990" \
-master.secondary="localhost:9991" \
-service.protocol="http" \
-serviceName="My Service" \
-proxy.port=":31900" \
-admin.port=":31159" \
-http.port=":31149" \
-rootUrl="localhost:31149"
```

It should be fine to remove most of the quotes, but I'm surprised that it still works with `-serviceName=My Service`.

The quotes are used for typical bash string concatenation, they shouldn't be passed to the program.

**Comment by puneetkhanduri** [comment]
@thomaska Thanks for catching this bug. PR welcome. Care to do the honors and remove the unnecessary escapes?
