### ISSUE TITLE
Diffy doesnt capture 'POST requests sent through proxy ports

### ISSUE THREAD

**Issue by sri85** [twitter/diffy#14]
I have an endpoint in my  service which accepts ` POST ` requests My curl request looks something like this 
` curl localhost:31900/messages -H "Content-type: application/json" -X POST -d
{"message":"Yello"} ' ` But i do not see traffic on my server side when using ` diffy  `

If i do normal ` curl ` request i.e without using diffy as a proxy  it works just fine. 

Looks like the ` POST request ` doesn't get through the proxy 
![image](https://cloud.githubusercontent.com/assets/1334423/9763193/2e7f591a-5700-11e5-90eb-31d154e4b0fb.png)

Does ` diffy ` support ` POST ` requests ?

**Comment by puneetkhanduri** [comment]
Yes you can replay post requests. See https://github.com/twitter/diffy/issues/9

We should update the documentation because this keeps coming up. Care to do the honors?

**Comment by sri85** [comment]
Cheers! Sure

**Comment by sri85** [comment]
@puneetkhanduri Have raised the pull request for the same

**Comment by puneetkhanduri** [comment]
https://github.com/twitter/diffy/pull/15
