### ISSUE TITLE
An example of diffy running on docker-compose

### ISSUE THREAD

**Issue by camiloribeiro** [twitter/diffy#17]
It is not an issue :) It is a humble example of how to your your amazing new tool locally, so people don't have to spend sometime deploying everything locally or setting it up just to try diffy. 

https://github.com/camiloribeiro/dockdiffy

It is based in the Dockerfile I just pull requested to you. Let me know your thoughts.

**Comment by puneetkhanduri** [comment]
@camiloribeiro I might suggest sending a PR with your docker example as a sub directory within diffy. The project is still very nascent and with a small number of contributors we might all benefit from sticking together and keeping everything in one place. That said, you are most welcome to maintain docdiffy as an independent project. Cheers!

**Comment by camiloribeiro** [comment]
@puneetkhanduri Thanks for replying :+1:  I will PR the docker-compose configuration tonight. Cheers!
