### ISSUE TITLE
Diffy relies too much in the content-type header

### ISSUE THREAD

**Issue by camiloribeiro** [twitter/diffy#18]
I was running some tests here to know how it works, and in one of my tests I have the following setup:

service primary:
    - content-type header => application/json
    - response-body => { "hello_world" : "primary" }

service secondary:
    - content-type header => application/json
    - response-body => { "hello_world" : "secondary" }

service candidate:
    - content-type header => application/**xml**
    - response-body => { "hello_world" : "candidate" }

In this scenario the diffy never checks the response and hangs forever.

Another test that I did could give you some more context on that issue. The test data in that case is the following:

service primary:
    - response code => **401**
    - content-type header => application/**json**
    - response-body => { "hello_**world**" : "primary" }

service secondary:
    - response code => **402**
    - content-type header => application/**xml**
    - response-body => { "hello_**foo**" : "secondary" }

service candidate:
    - response code => **403**
    - content-type header => application/**text**
    - response-body => { "hello_**bar**" : "candidate" }

In this case diffy holds for a long time, something around 40 seconds, and returns saying that everything is fine and there is no difference in the responses.

In a third scenario for this issue, if I use the same response code for primary and secondary, it returns fast as usual, but still without differences.

Please let me know if you have any questions regarding the scenarios. I am using my docker-compose setup to test it, so if you need feel free to clone it.

**Comment by puneetkhanduri** [comment]
Issue resolved in https://github.com/opendiffy/diffy
