### ISSUE TITLE
Encounter a problem while setting up diffy tutorial...

### ISSUE THREAD

**Issue by ianking** [twitter/diffy#20]
hi,

i encountered a problem while setting up the tutorial...
and that is probably due to the header "Host" sent by the diffy.

the tutorial has 3 urls, 
1. http://http-candidate.herokuapp.com
2. http://http-primary.herokuapp.com
3. http://http-secondary.herokuapp.com

and here is the traffic from diffy,
1. http://http-candidate.herokuapp.com
   174.129.192.57
   GET / HTTP/1.1
   Host: localhost:8990
   User-Agent: curl/7.43.0
   Accept: _/_
   Canonical-Resource: Html
2. http://http-primary.herokuapp.com
   174.129.192.57
   GET / HTTP/1.1
   Host: localhost:8990
   User-Agent: curl/7.43.0
   Accept: _/_
   Canonical-Resource: Html
3. http://http-secondary.herokuapp.com
   54.83.197.202
   GET / HTTP/1.1
   Host: localhost:8990
   User-Agent: curl/7.43.0
   Accept: _/_
   Canonical-Resource: Html

it seems 1. and 2. are in the same instance, and depend on "Host" to determine the response, but the  header "Host" from diffy is "localhost:8990", so the services always return 404...

removing the filter of Host from server or using the diffy proxy to change Host to http-xxxxx.herokuapp.com (the value from example.sh) may help.

![2015-09-22 2 24 40](https://cloud.githubusercontent.com/assets/5450486/10012025/c081aed2-6135-11e5-9642-e643dcfaf52a.png)

![2015-09-22 2 24 57](https://cloud.githubusercontent.com/assets/5450486/10012030/c6e685b8-6135-11e5-87aa-10b7e26af80a.png)

**Comment by scottclem** [comment]
I am also experiencing this issue.

**Comment by suoinguon** [comment]
I'm also experiencing this issue, look like diffy resolve hostname into IP before sending the request

**Comment by jamesweb1** [comment]
How do you see the traffic from diffy? I also get the same response(404) as yours...
How to solve this issue?
