### ISSUE TITLE
Can't access twitter maven repository, need packaged jar

### ISSUE THREAD

**Issue by jinkerry** [twitter/diffy#22]
hi, puneet

when i installed sbt and scala, then run ./stb assembly, it will return so much exception.

```
[error] Server access Error: Connection reset url=https://repo1.maven.org/maven2/com/twitter/finagle-thrift_2.11/6.28.0/finagle-thrift_2.11-6.28.0.pom
[error] Server access Error: Operation timed out url=https://maven.twttr.com/com/twitter/finagle-thrift_2.11/6.28.0/finagle-thrift_2.11-6.28.0.pom
```

I am in China, the network is so bad.
My proxy can not access twitter maven repository.
So, Could you mail a diffy-server.jar to me(jinkerrymail@gmail.com).
Thank you so much.

**Comment by camiloribeiro** [comment]
Hi @jinkerry. If you know how to use docker you can docker pull camiloribeiro/twitter-diffy.

It is a image that runs twitter-diffy in the current version. If you want to checkout the example you can find it here: https://github.com/camiloribeiro/dockdiffy (it is in process to be merged in this repo).

To run it with your service without docker compose you can run:
docker run -it camiloribeiro/twitter-diffy java -jar ./target/scala-2.11/diffy-server.jar -candidate='CANDIDATE_HOST_AND_PORT' -master.primary='PRYMARY_HOST_AND_PORT' -master.secondary='SECONDARY_HOST_AND_PORT' -service.protocol='http' -serviceName='Happy Service' -proxy.port=:31900 -admin.port=:8881 -http.port=:8888 -rootUrl='localhost:8888'

If you want, you can also ssh into the docker container and get the jar fine :)

If it fix your problem please close the issue. Thanks.

**Comment by jinkerry** [comment]
hi, @camiloribeiro 

I have run the docker container success, thank you very much.

ps: Because of The National Day of China, so reply late about 7 days, so so sorry.

**Comment by camiloribeiro** [comment]
@jinkerry You're welcome! Enjoy and have a nice weekend.
