### ISSUE TITLE
Does diffy support cookies?

### ISSUE THREAD

**Issue by diffyuser** [twitter/diffy#23]
I've set up diffy server and tried to use curl with cookies file(cookies from primary, secondary and candidate) to main proxy, e.g.:

> curl -b cookies.txt localhost:31900

Actually no luck, it doesn't seem that cookies were applied, and responses look like i've not passed authentication.

Does diffy support cookies or whethere there is any convinient way to pass authentication, as far as i need to be logged in befor performing any actions?

**Comment by sukalpomitra** [comment]
I do have a similar question too.All of our apis would need an accessToken to be set in the headers. Multicasting will result in 401 in 2 of the servers.

**Comment by sukalpomitra** [comment]
@diffyuser I have added support to pass different header value pairs to the different servers. Its in my forked repository. Also if your cookies key value pairs are same I guess you can pass them as --H "userrole:admin"
