### ISSUE TITLE
How to test DockerDiffy

### ISSUE THREAD

**Issue by benjelloun23** [twitter/diffy#27]
Hello,

I can't clone this : git clone git@github.com:camiloribeiro/dockdiffy.git
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

and for docker-compose up : bash: docker-compose: command not found

Can some one help me please.
Thanks.

**Comment by camiloribeiro** [comment]
try: git clone https://github.com/camiloribeiro/dockdiffy.git

to use docker compose you have to install it along with docker.
It is already installed with docker-machine. If you are not using it, try https://docs.docker.com/compose/install/

**Comment by mosesn** [comment]
@benjelloun23 if you want to use the git protocol to clone, you must make sure that you have the right ssh keys on your machine.  If you have more than one set of ssh keys, you may have to explicitly specify the one you use for github with `ssh-add`.

**Comment by benjelloun23** [comment]
Hello,
this is my steps to install docker compose but still not working :s 

1. I launch docker quiq terminal then i run this command : 
> curl -L https://github.com/docker/compose/releases/download/1.4.2/docker-compose-`uname -s`-`uname -m` > /c/program/Docker\ Toolbox/docker-compose
> chmod +x /c/program/Docker\ Toolbox/docker-compose

2.. A file was created "docker-compose" which contain {"error":"Not Found"}

3. I run command : > docker-compose --version and i have this error: /c/Program Files/Docker Toolbox/docker-compose: line 1: {error:Not Found}: command not found

I need some help please
