### ISSUE TITLE
Add protobuf support to Diffy

### ISSUE THREAD

**Issue by thinkerou** [twitter/diffy#29]
diffy is a regression detection system for thrift and http services, so I want it for protobuffer, do I need other? Thanks.

**Comment by puneetkhanduri** [comment]
@mosesn Is there a recommended way to support protobuf with Finagle?

**Comment by mosesn** [comment]
Sorry just saw this.  We don't use it internally, but [finagle/finagle-protobuf](https://github.com/finagle/finagle-protobuf) is the right way, as far as I know.

**Comment by puneetkhanduri** [comment]
@thinkerou protobuf is not supported out of the box but it should be possible to do so by leveraging the library mentioned above. Unfortunately, you won't be able to use Diffy without writing the necessary support for protobuf. Let me know if there is interest on your part to make this change.

**Comment by thinkerou** [comment]
@puneetkhanduri our web server uses protobuf, so I want to use Diffy in order to automated test.

**Comment by puneetkhanduri** [comment]
@thinkerou Currently, this is not possible. We will have to leave this issue open as a feature request for now.
