### ISSUE TITLE
Having trouble getting Diffy to separate endpoints

### ISSUE THREAD

**Issue by thelaurence** [twitter/diffy#30]
As I send requests to Diffy, all the results are lumped together under a single title: "Undefined_endpoint." It looks like this:

![screenshot from 2015-11-19 13 49 57](https://cloud.githubusercontent.com/assets/10649804/11284013/c2f6c190-8ec4-11e5-9656-210b74005976.png)

What do I need to do to have each endpoint get its own label?

**Comment by puneetkhanduri** [comment]
Per endpoint bucketing in Diffy requires either the request to have a "Canonical-Resource" header or the responses from the targets to have an "X-Action-Name" header with the endpoint name as the value.

**Comment by thelaurence** [comment]
Thanks!
