### ISSUE TITLE
NumberFormatException when specifying a context after port

### ISSUE THREAD

**Issue by davidlinse** [twitter/diffy#34]
Diffy does not work with a "_context_" after the port e.g.  `-candidate=myservice:port/CustomContext`. Feel free to have a look at this [gist](https://gist.github.com/davidlinse/9d5eda49332793d622ac#file-diffy-stacktrace-log) for the stacktrace.

regards
~david

**Comment by davidlinse** [comment]
Any news on this ?

**Comment by puneetkhanduri** [comment]
@davidlinse The relative path "/CustomContext" needs to be in each request meant for that path. Diffy simply forwards whatever requests it receives to your primary, secondary, and candidate with whatever path is included in the request.
