### ISSUE TITLE
How to pass on output of one service to another?

### ISSUE THREAD

**Issue by anandhravindran** [twitter/diffy#35]
Hi, this looks like an interesting tool. I wanted know how to get it working in one particular scenrio. Let's say if I have two services, createUser (http://myservice/createUser) and GetUserInfo (http://myservice/getUserInfo/{userId}).  The userId used in the second service is from the first service createUser response. 

In this scenario, 1) how do I get the first service' response and pass on to second service? 
2) Also the url that we hit proxy is sent to candidate, primary and secondary. If my userId is dynamic and varies across across 3 instances. How do I handle this scenario?

P.S: I don't know if this has been answered already. If that is the case , please point me to it

**Comment by sukalpomitra** [comment]
hi @anandhravindran I have added support toyour query 2 in my forked repository https://github.com/sukalpomitra/diffy. I may also add support to your point 1 if i get some free time. I am unable to create a pull request as of now.

**Comment by anandhravindran** [comment]
@sukalpomitra Thanks a lot for looking into this issue. Please let me know after you have added support for query 1.
