### ISSUE TITLE
cannot connnect to maven.twttr.com

### ISSUE THREAD

**Issue by dellenovo** [twitter/diffy#36]
Hi diffy's developers,

When I run ./sbt assemble, I find the connection error: 
[error] Server access Error: Connection timed out: connect url=https://maven.twttr.com/org/apache/thrift/libthrift/0.5.0-1/libthrift-0.5.0-1.pom
[warn]  module not found: org.apache.thrift#libthrift;0.5.0-1

My IT colleague has gotten rid of all firewalls but still cannot connect to the url. Could you please make sure if the url (or the resource representing by the url) is available.

Thanks in advance!
name: Lifei
email: zhanglifeifly@126.com

**Comment by mosesn** [comment]
Yes, it's available.  I think you might still be behind the GFW.

**Comment by valaxy** [comment]
can not access too behind a GFW, with a proxy either not.
