### ISSUE TITLE
sever candidate & server primary(diff) has different url

### ISSUE THREAD

**Issue by colozou** [twitter/diffy#37]
Hi diffy's developers,
If the sever candidate & server primary(diff) has different url, for ex, a.com/v1/getuser & a.com/v2/getuser, how should I write the conf, as long as I know, "-candidate" should be like this "ip:post".
Thanks!

**Comment by colozou** [comment]
I want write like this..
-candidate='*.*.*.*:8080/v1/web' \
-master.primary='*.*.*.*:8080/v2/web' \
-master.secondary='*.*.*.*:8080/v1/web' \

**Comment by sukalpomitra** [comment]
hi @colozou i have added support to add different api roots to the api calls. You can get it from my forked repository. I am still waiting to create a pull request.
