### ISSUE TITLE
Can you please add support for the response times too?

### ISSUE THREAD

**Issue by shiva404** [twitter/diffy#38]
I want track difference in response times b/w new release and the old one. I would like to contribute back to but if you are already thinking to add support for the same, I will wait for you else I will try to implement and I can contribute back.

**Comment by puneetkhanduri** [comment]
@shiva404 We've been experimenting with analyzing regressions in performance stats and we do have something in the pipeline. Perf stats are naturally more susceptible to noise and requires a more complex topology than what Diffy currently builds on so I have been hesitant to introduce a big change that might not produce enough value. Would love to hear your thoughts on how you are planning on isolating real performance regressions (slowed endpoints) from noise. Perhaps we can collaborate on this feature.
