### ISSUE TITLE
Sending different header content to different servers

### ISSUE THREAD

**Issue by sukalpomitra** [twitter/diffy#40]
HI this maybe a duplicate of Issue #23 and #37 . If it is so then please close this out.

We have different header www-authenticate (Basic Authentication Scheme) values that is sent while invoking the API endpoints. I am not sure if this support is already in diffy but if not I guess it will be better if we can add a feature where we can send different header key-pair values to different servers.

**Comment by sukalpomitra** [comment]
HI I have actually modified the code to inject headers before multicast. I will try to create a pull request.

**Comment by sukalpomitra** [comment]
I have forked the repository and have commited my changes. But unable to create a new pull request. Is the new pull request disabled somehow?

**Comment by puneetkhanduri** [comment]
Hi Sukalpo. You should be able send a PR. I have been able to merge PRs from other contributors so not sure what issues you might be seeing.

**Comment by sukalpomitra** [comment]
@puneetkhanduri able to do it now. Was comparing some different branch. My bad

**Comment by PilchardFriendly** [comment]
@sukalpomitra Not sure where you got to with your approach.  I've found the need for the same sort of features - have a look at #46 

@puneetkhanduri can you help us fix the Travis CI setup?

**Comment by sukalpomitra** [comment]
HI @PilchardFriendly I have accomplished adding the headers too. Not only the headers but also sending different queryparams to the different servers. Because I wanted to test get methods passing id which again are different in different servers. You can view my fork. But I need to refator the code a bit to make the travis build success mark, which I am not finding time for.
