### ISSUE TITLE
error: "object file is not a member of package java.nio"

### ISSUE THREAD

**Issue by linlone** [twitter/diffy#44]
my installation steps are following:

$ export https_proxy=https://10.210.239.82:3128
$ export http_proxy=http://10.210.239.82:3128

$ svn co https://github.com/twitter/diffy.git/trunk/

$ ./sbt assembly
downloading sbt-launch.jar
[info] Loading project definition from /home/wandongde/test11/trunk/project
[info] Updating {file:/home/wandongde/test11/trunk/project/}trunk-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to diffy (in build file:/home/wandongde/test11/trunk/)
[info] Updating {file:/home/wandongde/test11/trunk/}diffy...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  \* com.twitter:finagle-http_2.11:6.25.0 -> 6.28.0
[warn] Run 'evicted' to see detailed eviction warnings
[info] Generating scrooge thrift for /home/wandongde/test11/trunk/src/main/thrift/diffy.thrift ...
[info] Compiling 35 Scala sources to /home/wandongde/test11/trunk/target/scala-2.11/classes...
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/proxy/ClientService.scala:45: Procedure syntax is deprecated. Convert procedure `sizeChange` to method by adding `: Unit =`.
[warn]   private[this] def sizeChange(size: Int) {
[warn]                                           ^
[warn] /home/wandongde/test11/trunk/target/scala-2.11/src_managed/main/com/twitter/diffy/thriftscala/SampleService$FinagleService.scala:61: Procedure syntax is deprecated. Convert procedure `addFunction` to method by adding `: Unit =`.
[warn]   protected def addFunction(name: String, f: (TProtocol, Int) => Future[Array[Byte]]) {
[warn]                                                                                       ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/Main.scala:22: a pure expression does nothing in statement position; you may be omitting necessary parentheses
[warn]     proxy.server
[warn]           ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/workflow/Workflow.scala:40: implicit numeric widening
[warn]     scope.scope(endpoint).provideGauge("total"){ meta.total }
[warn]                                                       ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/workflow/Workflow.scala:41: implicit numeric widening
[warn]     scope.scope(endpoint).provideGauge("differences"){ meta.differences }
[warn]                                                             ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/analysis/JoinedDifferences.scala:23: postfix operator toSeq should be enabled
[warn] by making the implicit value scala.language.postfixOps visible.
[warn] This can be achieved by adding the import clause 'import scala.language.postfixOps'
[warn] or by setting the compiler option -language:postfixOps.
[warn] See the Scala docs for value scala.language.postfixOps for a discussion
[warn] why the feature should be explicitly enabled.
[warn]         } toSeq
[warn]           ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/compare/Difference.scala:137: abstract type A in type pattern scala.collection.immutable.Set[A](the underlying of Set[A]) is unchecked since it is eliminated by erasure
[warn]       case (ls: Set[A], rs: Set[A]) => diffSet(ls, rs)
[warn]                 ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/compare/Difference.scala:137: abstract type A in type pattern scala.collection.immutable.Set[A](the underlying of Set[A]) is unchecked since it is eliminated by erasure
[warn]       case (ls: Set[A], rs: Set[A]) => diffSet(ls, rs)
[warn]                             ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/compare/Difference.scala:138: non-variable type argument Any in type pattern com.twitter.diffy.lifter.FieldMap[Any] is unchecked since it is eliminated by erasure
[warn]       case (lm: FieldMap[Any], rm: FieldMap[Any]) => diffObjectMap(lm, rm)
[warn]                 ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/compare/Difference.scala:138: non-variable type argument Any in type pattern com.twitter.diffy.lifter.FieldMap[Any] is unchecked since it is eliminated by erasure
[warn]       case (lm: FieldMap[Any], rm: FieldMap[Any]) => diffObjectMap(lm, rm)
[warn]                                    ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/compare/Difference.scala:139: abstract type A in type pattern scala.collection.immutable.Map[A,Any](the underlying of Map[A,Any]) is unchecked since it is eliminated by erasure
[warn]       case (lm: Map[A, Any], rm: Map[A, Any]) => diffMap(lm, rm)
[warn]                 ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/compare/Difference.scala:139: abstract type A in type pattern scala.collection.immutable.Map[A,Any](the underlying of Map[A,Any]) is unchecked since it is eliminated by erasure
[warn]       case (lm: Map[A, Any], rm: Map[A, Any]) => diffMap(lm, rm)
[warn]                                  ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/lifter/HtmlLifter.scala:24: postfix operator toMap should be enabled
[warn] by making the implicit value scala.language.postfixOps visible.
[warn]           } toMap
[warn]             ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/lifter/ThriftLifter.scala:174: implicit numeric widening
[warn]         case None => throw FieldOutOfBoundsException(field.id)
[warn]                                                            ^
[error] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/scrooge/ThriftImporter.scala:5: object file is not a member of package java.nio
[error] import java.nio.file.Files
[error]                 ^
[error] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/scrooge/ThriftImporter.scala:12: not found: value Files
[error]     val thriftDir = Files.createTempDirectory("thrift-")
[error]                     ^
[error] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/scrooge/ThriftImporter.scala:23: not found: value Files
[error]           Files.write(newFile.toPath, data.getBytes)
[error]           ^
[error] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/scrooge/ThriftImporter.scala:33: not found: value Files
[error]     val thriftDir = Files.createTempDirectory("thrift-")
[error]                     ^
[error] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/scrooge/ThriftImporter.scala:38: not found: value Files
[error]       Files.copy(file.toPath, newFile.toPath)
[error]       ^
[error] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/scrooge/ThriftImporter.scala:38: value toPath is not a member of java.io.File
[error]       Files.copy(file.toPath, newFile.toPath)
[error]                       ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/scrooge/ThriftImporter.scala:5: Unused import
[warn] import java.nio.file.Files
[warn]                      ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/util/EmailSender.scala:41: This catches all Throwables. If this is really intended, use `case e : Throwable` to clear this warning.
[warn]       } catch { case e =>
[warn]                      ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/workflow/ReportGenerator.scala:71: implicit numeric widening
[warn]           joinedEndpoint.total,
[warn]                          ^
[warn] /home/wandongde/test11/trunk/src/main/scala/com/twitter/diffy/workflow/Workflow.scala:5: Unused import
[warn] import com.twitter.diffy.analysis.{RawDifferenceCounter, DifferenceCounter, EndpointMetadata}
[warn]                                                          ^
[warn] 18 warnings found
[error] 6 errors found
[error](compile:compileIncremental) Compilation failed
[error] Total time: 23 s, completed Jun 14, 2016 3:39:43 PM

Pls help check why fail. thanks

**Comment by sukalpomitra** [comment]
Hi, Please check if you are using Java 6 or lower. You need to be in Java 7 or higher.

**Comment by sukalpomitra** [comment]
HI @linlone is your issue resolved?
