### ISSUE TITLE
where is the libthrift put in my local disk? 

### ISSUE THREAD

**Issue by plscomeon** [twitter/diffy#45]
![image](https://cloud.githubusercontent.com/assets/6880553/16170048/4e50ea96-3577-11e6-837c-a60ade3e5761.png)

**Comment by plscomeon** [comment]
bcs i can't connect to "http://maven.twttr.com/" for download the "libthrift-0.5.0.jar" buy build. but i can get the jar from other way.

**Comment by neven7** [comment]
so am i

**Comment by puneetkhanduri** [comment]
Unfortunately, the only way forward I can recommend here is to retry until you are able to connect to twitter maven repo.

**Comment by mosesn** [comment]
@puneetkhanduri we have now published a new copy of libthrift to maven central under the organization com.twitter.  http://search.maven.org/#artifactdetails%7Ccom.twitter%7Clibthrift%7C0.5.0-7%7Cjar

**Comment by puneetkhanduri** [comment]
Thanks @mosesn.

@neven7 @plscomeon It seems you should be unblocked now.
