### ISSUE TITLE
Cannot start diffy, blocked by "./sbt assembly"

### ISSUE THREAD

**Issue by helloparrotking** [twitter/diffy#55]
Updated on Jan 11th:
When I ran sh example.sh
I got 
./target/scala-2.11/diffy-server.jar中没有主清单属性
What can I do?
--------------------------------------------------------------------------------------
Hi,
  I just got the diffy code and then ran the "./sbt assembly" as the wiki says. It shown updating a lot of dependencies  at first, but than ,it was blocked, end with something like this:

_...(Omit)_
[info] 	[SUCCESSFUL ] javax.activation#activation;1.1!activation.jar (773ms)
[info] downloading https://repo1.maven.org/maven2/com/twitter/finatra/finatra-jackson_2.11/2.0.0.M2/finatra-jackson_2.11-2.0.0.M2.jar ...
[info] 	[SUCCESSFUL ] com.twitter.finatra#finatra-jackson_2.11;2.0.0.M2!finatra-jackson_2.11.jar (1302ms)
[info] downloading https://repo1.maven.org/maven2/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar ...
[info] 	[SUCCESSFUL ] commons-fileupload#commons-fileupload;1.3.1!commons-fileupload.jar (916ms)
[info] downloading https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar ...
[info] 	[SUCCESSFUL ] javax.servlet#servlet-api;2.5!servlet-api.jar (1229ms)
[info] downloading https://repo1.maven.org/maven2/com/twitter/finatra/finatra-utils_2.11/2.0.0.M2/finatra-utils_2.11-2.0.0.M2.jar ...
[info] 	[SUCCESSFUL ] com.twitter.finatra#finatra-utils_2.11;2.0.0.M2!finatra-utils_2.11.jar (1525ms)
[info] downloading https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.4.4/jackson-databind-2.4.4.jar ...
_(end here)_

It totally stopped. I have no idea. Maybe I should install the SBT, or other necessary softwares? Since I am from China, and I use MAVEN as the build tool, my OS is mac, maybe there are some different between our environments. Hope getting answers soon~ Thank you

**Comment by yulongsg** [comment]
请问搞定了吗

**Comment by puneetkhanduri** [comment]
I am not sure why some dependencies might not be resolving for you. It could be a network firewall constraint but it is impossible for me to guess. Anyhow, if you just want to use Diffy then you can download the prebuilt jar from maven at http://repo1.maven.org/maven2/com/twitter/diffy_2.11/0.0.1/diffy_2.11-0.0.1.jar
