### ISSUE TITLE
"(more on thresholds)" link points to a non-existant page

### ISSUE THREAD

**Issue by ramunasm** [twitter/diffy#56]
https://github.com/twitter/diffy/blob/2077282cc2e17ee6ae636a01492a78b9c5ea644d/src/main/resources/templates/dashboard.mustache#L113

The following link points to: http://go/diffy/thresholds.html, which is not a valid URL? Am I missing something?

Thank you

**Comment by andypiper** [comment]
That's a convenience link to an internal page and only relevant where Diffy is running inside Twitter.

**Comment by puneetkhanduri** [comment]
Removed as it is not relevant to the github project.
