### ISSUE TITLE
Is it possible to show POST request body?

### ISSUE THREAD

**Issue by ramunasm** [twitter/diffy#57]
Hello,

Is there a way to see the POST body of the request which "triggered" the difference?
As right now I'm just seeing the URL and IP address of the sender.

![screen shot 2017-04-06 at 09 32 09](https://cloud.githubusercontent.com/assets/1158178/24741035/ca500f76-1aac-11e7-8cfb-c3143eaa8c77.png)

**Comment by puneetkhanduri** [comment]
it should show up with the latest master now.
