### ISSUE TITLE
Feature Request: Support ignoring noisy fields

### ISSUE THREAD

**Issue by sunnybayz** [twitter/diffy#59]
My understanding is that Diffy saves all the responses with differences in memory. In one of our services, the service returns a random UUID in the response. Therefore, when "Exclude Noise" is disabled, it shows 100% diff. When "Exclude Noise" is enabled, it shows very low percentage diff. Diffy frequently runs out of memory because it saves 100% of the responses.

Is it possible to configure Diffy in a way that it simply discard the responses that only differ in noisy fields? That way, it can process much more requests without running out of memory.

Another solution is to support ignoring certain fields for comparison. The ignored fields can be set in command line.

Thanks!

**Comment by puneetkhanduri** [comment]
Diffy does not save all results in memory - only a subset of samples so that it doesn't run out of memory. Without having access to a heapdump it will be impossible to say what might be causing a memeory leak in your specific case.

**Comment by sunnybayz** [comment]
That's really good to know! I will try to get a heapdump.

**Comment by fwz** [comment]
May I know whether Diffy support excluding specific key now? @puneetkhanduri 

For example, we have a v1 API, with key 'a' in response.  And then we implement a v2 API to add another key 'b' in response. We want to use Diffy to ensure the value of 'a' are exactly the same for both versions.

**Comment by puneetkhanduri** [comment]
The Diffy UI allows you to manually click and ignore certain keys. This selection exists purely in the UI and has no impact on the Diffy server.
Side: Please open future support requests on [Opendiffy](https://github.com/opendiffy/diffy).
