### ISSUE TITLE
Logic that chooses the 5 displayed differences

### ISSUE THREAD

**Issue by ramunasm** [twitter/diffy#61]
Hello,

I would like to know what is the logic behind choosing the 5 differences to be displayed? How does it work?
Also, is it possible to somehow see more differences?

Thank you!

**Comment by puneetkhanduri** [comment]
The reason for limiting the chosen differences to 5 is to implicitly limit storage requirements. From a product perspective, for most use cases 5 examples of an error provide sufficient feedback to the developer to fix the problem.

It is possible to see all the differences by enabling debug logs. Specifically, you should look for "differences.log".
