### ISSUE TITLE
support grpc

### ISSUE THREAD

**Issue by thinkerou** [twitter/diffy#67]
I want to use it for `grpc`, support?

**Comment by puneetkhanduri** [comment]
Diffy currently supports Thrift rpc. Contributions welcome for grpc+protobuf.

**Comment by thinkerou** [comment]
OK, thanks @puneetkhanduri . My projects use grpc+protobuf now, so we will try to support them.

**Comment by puneetkhanduri** [comment]
Would love to learn more about your use case and see if we can collaborate on this. Let me know if you want to jump on a quick call.

**Comment by thinkerou** [comment]
Now I have many interface case and I spend time to maintain them. So I want to use `diffy` which only support thrift and http/https. Next I need to read the code of `diffy` to understand it and try to support `grpc`.

**Comment by puneetkhanduri** [comment]
@thinkerou I can explain the code to you as you add support fo grpc. let me know if you need help. i am happy to jump on a video cal and we can screenshare and pair up.

**Comment by thinkerou** [comment]
OK, thanks a lot @puneetkhanduri ,  sorry for the late replay and been busy recently,  I will begin after a while and contact you.
