### ISSUE TITLE
WebSocket support

### ISSUE THREAD

**Issue by vooolll** [twitter/diffy#74]
Is it possible to test services based on web sockets with `diffy`?

**Comment by opendiffy** [comment]
At a networking level - yes - as long as your application still follows request-response (RPC) semantics. If you are using websockets for streaming then it becomes tricky to define what to compare across two different versions of the code. With [opendiffy](https://github.com/opendiffy/diffy) we are piloting this concept with a beta user and trying to solve the problem in a generally useful way. If you are up for it we would love to understand your use case and see if our solution works for you.
