### ISSUE TITLE
How to export data from the server

### ISSUE THREAD

**Issue by pedromss** [twitter/diffy#76]
Is there a way to get a representation of the differences? 

If not, is this something you would accept? Perhaps through an HTTP endpoint?

The use case for this is to be able to reset Diffy but keep the data regarding the differences.

**Comment by puneetkhanduri** [comment]
You can fetch the differences via the json api used to power the UI.

Take a look at https://github.com/opendiffy/diffy/blob/master/src/main/scala/com/twitter/diffy/ApiController.scala

Let me know if you have something else in mind.

**Comment by pedromss** [comment]
Just discovered the JSON API last night while looking at the code. My first suggestion here would be to include this API in the README so people know it exists.

Looking at the API it appears one can:
- Retrieve the list of differences through: `/api/1/endpoints/:endpoint/stats`
- Retrieve the details of a specific difference through: `/api/1/endpoints/:endpoint/fields/:path/results`
- More things...

The next step for this would be to include 2 buttons in the UI + 1 more endpoint:
- The additional endpoint would send the entire difference + details for each endpoint (without the need to specify a path, all paths would be returned)
- 1 button in the UI to **download** the differences **to** a file
- 1 button in the UI to **upload** the differences **from** a file


As mentioned before the use case for this is to be able to reset Diffy keeping the differences data. The **upload** button is so people can see the old differences they downloaded in the UI which is a nicer way to view the differences, especially if you are presenting to more people.

If for some reason I'm missing something and one can already download and upload the differences currently in memory, please let me know.
