### ISSUE TITLE
fail to started

### ISSUE THREAD

**Issue by LeonZXY** [twitter/diffy#78]
failed with following error :

[error] Server access Error: Operation timed out (Connection timed out) url=https://maven.twttr.com/org/apache/httpcomponents/httpcomponents-core/4.1.4/httpcomponents-core-4.1.4.jar
[info] Resolving commons-logging#commons-logging;1.1.1 ...
[error] SERVER ERROR: Gateway Time-out url=https://repo.typesafe.com/typesafe/ivy-releases/commons-logging/commons-logging/1.1.1/ivys/ivy.xml
[info] Resolving org.apache#apache;4 ...
[error] Server access Error: Operation timed out (Connection timed out) url=https://maven.twttr.com/org/apache/apache/4/apache-4.jar
[error] Server access Error: Operation timed out (Connection timed out) url=https://maven.twttr.com/org/apache/commons/commons-parent/5/commons-parent-5.jar
[info] Resolving org.apache#apache;4 ...
[error] Server access Error: Operation timed out (Connection timed out) url=https://maven.twttr.com/org/apache/commons/commons-parent/11/commons-parent-11.jar
[info] Resolving org.apache#apache;13 ...
[error] Server access Error: Operation timed out (Connection timed out) url=https://maven.twttr.com/org/apache/apache/13/apache-13.jar
[error] Server access Error: Operation timed out (Connection timed out) url=https://maven.twttr.com/org/apache/commons/commons-parent/32/commons-parent-32.jar
[info] Resolving org.apache.thrift#libthrift;0.5.0-1 ...
[error] Server access Error: Operation timed out (Connection timed out) url=https://maven.twttr.com/org/apache/thrift/libthrift/0.5.0-1/libthrift-0.5.0-1.pom

I can ping these URLs, but when I access  them in browser there is nothing to access

**Comment by puneetkhanduri** [comment]
Can you try https://github.com/opendiffy/diffy and move this issue there if it is still a problem.
