### ISSUE TITLE
fail to get started diffy

### ISSUE THREAD

**Issue by LeonZXY** [twitter/diffy#79]
When I downloaded the code using 'git clone https://github.com/twitter/diffy.git'，and then run the commend with './example/run.sh start'. And then it had been stopped by an error. The detail of logs like followings:

[error] Server access Error: Operation timed out (Connection timed out) url=https://maven.twttr.com/org/apache/thrift/libthrift/0.5.0-1/libthrift-0.5.0-1.pom
[warn] 	module not found: org.apache.thrift#libthrift;0.5.0-1

I can access the url “https://maven.twttr.com/org/apache/thrift/libthrift/0.5.0-1/libthrift-0.5.0-1.pom” in browser. But it didn't work in starting the diffy.

How can I fix this?

**Comment by puneetkhanduri** [comment]
https://github.com/twitter/diffy/issues/78
