### ISSUE TITLE
sbt.ResolveException: unresolved dependency: org.apache.thrift#libthrift;0.5.0-1: not found

### ISSUE THREAD

**Issue by LeonZXY** [twitter/diffy#80]
When I downloaded the code using 'git clone https://github.com/twitter/diffy.git'，and then run the commend with './example/run.sh start'. And then it had been stopped by an error. The detail of logs like followings:

[info] Resolving org.apache.thrift#libthrift;0.5.0-1 ...
[error] Server access Error: Operation timed out (Connection timed out) url=https://maven.twttr.com/org/apache/thrift/libthrift/0.5.0-1/libthrift-0.5.0-1.pom
[warn] 	module not found: org.apache.thrift#libthrift;0.5.0-1
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.apache.thrift/libthrift/0.5.0-1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.apache.thrift/libthrift/0.5.0-1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/renwei/.ivy2/local/org.apache.thrift/libthrift/0.5.0-1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.5.0-1/libthrift-0.5.0-1.pom
[warn] ==== Twitter's Repository: tried
[warn]   https://maven.twttr.com/org/apache/thrift/libthrift/0.5.0-1/libthrift-0.5.0-1.pom
[warn] ==== jgit-repo: tried
[warn]   http://download.eclipse.org/jgit/maven/org/apache/thrift/libthrift/0.5.0-1/libthrift-0.5.0-1.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.apache.thrift#libthrift;0.5.0-1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.apache.thrift:libthrift:0.5.0-1
[warn] 		  +- com.twitter:scrooge-generator_2.10:4.0.0
[warn] 		  +- com.twitter:scrooge-sbt-plugin:4.0.0 (scalaVersion=2.10, sbtVersion=0.13) (/Users/renwei/soft/diffy/project/plugins.sbt#L9-10)
[warn] 		  +- default:diffy-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: org.apache.thrift#libthrift;0.5.0-1: not found

How can I fix this?

**Comment by puneetkhanduri** [comment]
https://github.com/twitter/diffy/issues/78
