### ISSUE TITLE
Diffy admin won't load, no errors, StaticLoggerBinder warning

### ISSUE THREAD

**Issue by franhaselden** [twitter/diffy#85]
Tried running both the example in the documentation and with my own servers. I'm running with Docker.

I get no errors, except a warning:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Admin pane won't load either (404) on `http://localhost:8888/admin/`

The Diffy interface loads and shows the expected candidate server, primary server and secondary server along with correct reset and change times, but it simply won't load any further nor give any errors

**Comment by benjamin-bergia** [comment]
See issue here. running the 20180711 image works but not latest.

**Comment by benjamin-bergia** [comment]
It looks like the latest image on docker hub has an issue. It is way smaller in size and after running docker build and running the master, I have issues. Would it be possible to rebuild and push the latest?

**Comment by puneetkhanduri** [comment]
Please migrate to https://github.com/opendiffy/diffy. This repo is very old and hasn't been upgraded in a while.

**Comment by thinkerou** [comment]
@puneetkhanduri consider to archive the repo which only support to read? thanks!
