### ISSUE TITLE
Add Opentracing to diffy.

### ISSUE THREAD

**Issue by flouthoc** [twitter/diffy#88]
Hi Team, 
I would like to request open tracing like feature request for diffy which could dig further into the microservices  pipeline and highlight the exact point causing the difference.

**Comment by puneetkhanduri** [comment]
This is outside the scope of Diffy as it works purely as a network proxy while distributed tracing (like OpenTracing implementations) requires context propagation at the service framework level. We have a different project called Isotope that enables this. You are welcome to apply for beta access [here](https://goo.gl/forms/SVkgZg6oUOXSO14b2)

**Comment by flouthoc** [comment]
@puneetkhanduri  Thanks for the isotope access.
