### ISSUE TITLE
Are posts supported?

### ISSUE THREAD

**Issue by PatrickWalker** [twitter/diffy#9]
The examples at the minute are all Http GETS.

Does Diffy currently support posts?

I've tried sending a few in but it doesn't seem to be acknowledged by Diffy as I can't see the post being forwarded on to the service nor any results entered?

I've tried adding the Canonical-Resource header as well but with no luck so far

curl  --header "Canonical-Resource: Html"  -H "Content-Type: application/json" -X POST -d '{"foo":"bar"}' http://localhost:8880

Is my request at the minute or a scaled down version. Probably doing something stupid!

**Comment by puneetkhanduri** [comment]
POST, PUT, DELETE are ignored by default for safety. You can enable them by explicitly adding the following flag to your diffy deploy command:

-allowHttpSideEffects=true

**Comment by PatrickWalker** [comment]
Thanks!

That got it
