### ISSUE TITLE
Dashboard script files path

### ISSUE THREAD

**Issue by sergioasantiago** [twitter/diffy#94]
In order to use the Dashboard behind an api gateway, that forward the path to the underneath service, we should be able to specify in the dashboard html the apiRoot, and prefix it to the scripts (.js/.css) files path.

In our use case, we have the apigateway that proxy the requests and redirect it to the underneath service. We have configured the apiRoot variable to /diffyservice, which works ok for the calls made by the js scripts, but the Dashboard html is not reflecting the same behaviour.

I suggest to add the {{apiRoot}} to the scripts path in order to fix it.

I can create the PR if needed.

**Comment by puneetkhanduri** [comment]
https://github.com/opendiffy/diffy/issues/20
