### ISSUE TITLE
manifest for hseeberger/scala-sbt not found

### ISSUE THREAD

**Issue by NedkoHristov** [twitter/diffy#97]
# Issue
Trying to run Diffy on container, but receive next error:

`$ docker build -t diffy .
Sending build context to Docker daemon  2.648MB
Step 1/8 : FROM hseeberger/scala-sbt
manifest for hseeberger/scala-sbt not found`

# Fix
@hseeberger mention the [change of versioning in tags](https://github.com/hseeberger/scala-sbt/issues/76).
Fix is to add tag to the docker image.
Before:
`FROM hseeberger/scala-sbt`

To:
`FROM hseeberger/scala-sbt:8u212_1.2.8_2.13.0`

I tried to make a PR, but didn't have permissions to do that.

**Comment by puneetkhanduri** [comment]
Please consider migrating to https://github.com/opendiffy/diffy. This problem and many others have already been fixed there.

**Comment by puneetkhanduri** [comment]
@NedkoHristov : Also, if you are just trying to run Diffy you can bypass building it and just pull the latest image from dockerhub via `docker pull diffy/diffy`

**Comment by NedkoHristov** [comment]
Thanks, @puneetkhanduri. Already clone the opendiffy.

It would be good if at the beginning of the README.MD is mentioned that this repo is not maintained.
